In [164]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

import warnings 
warnings.filterwarnings('ignore')

In [165]:
df = sns.load_dataset('mpg')

In [166]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [167]:
df.drop("name", axis=1, inplace=True)

In [168]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa

In [169]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [170]:
df['horsepower'].median()

np.float64(93.5)

In [171]:
df['horsepower']=df['horsepower'].fillna(df["horsepower"].median())

In [172]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [173]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

In [174]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin           object
dtype: object

In [175]:
df['origin'].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [176]:
df['origin'].map({"usa":1, "japan":2, "europe":3})

0      1
1      1
2      1
3      1
4      1
      ..
393    1
394    3
395    1
396    1
397    1
Name: origin, Length: 398, dtype: int64

In [177]:
df['origin'] = df['origin'].map({"usa":1, "japan":2, "europe":3})

In [178]:
df['origin'] = df['origin'].astype(int)

In [179]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin            int64
dtype: object

In [180]:
# separate X and y

x = df.drop('mpg', axis=1)
y = df['mpg']

In [181]:
x

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,8,307.0,130.0,3504,12.0,70,1
1,8,350.0,165.0,3693,11.5,70,1
2,8,318.0,150.0,3436,11.0,70,1
3,8,304.0,150.0,3433,12.0,70,1
4,8,302.0,140.0,3449,10.5,70,1
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1
394,4,97.0,52.0,2130,24.6,82,3
395,4,135.0,84.0,2295,11.6,82,1
396,4,120.0,79.0,2625,18.6,82,1
397,4,119.0,82.0,2720,19.4,82,1

In [182]:
y

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [183]:
# train test splite 

from sklearn.model_selection import train_test_split

In [184]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=1)

In [185]:
x_train

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
192,6,250.0,105.0,3353,14.5,76,1
27,8,318.0,210.0,4382,13.5,70,1
89,8,318.0,150.0,3777,12.5,73,1
310,4,89.0,60.0,1968,18.8,80,2
73,8,307.0,130.0,4098,14.0,72,1
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1
255,4,140.0,88.0,2720,15.4,78,1
72,8,304.0,150.0,3892,12.5,72,1
235,4,97.0,75.0,2265,18.2,77,2
37,6,232.0,100.0,3288,15.5,71,1

In [186]:
x_test

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
174,6,171.0,97.0,2984,14.5,75,1
359,4,141.0,80.0,3230,20.4,81,3
250,8,318.0,140.0,3735,13.2,78,1
274,5,131.0,103.0,2830,15.9,78,3
283,6,232.0,90.0,3265,18.2,79,1
...,...,...,...,...,...,...,...
107,6,232.0,100.0,2789,15.0,73,1
331,4,97.0,67.0,2145,18.0,80,2
172,4,90.0,71.0,2223,16.5,75,3
82,4,120.0,97.0,2506,14.5,72,2
366,6,225.0,85.0,3465,16.6,81,1

In [187]:
y_train

192    22.0
27     11.0
89     15.0
310    38.1
73     13.0
       ...
393    27.0
255    25.1
72     15.0
235    26.0
37     18.0
Name: mpg, Length: 298, dtype: float64

In [188]:
y_test

174    18.0
359    28.1
250    19.4
274    20.3
283    20.2
       ...
107    18.0
331    33.8
172    25.0
82     23.0
366    17.6
Name: mpg, Length: 100, dtype: float64

In [189]:
# simple linear regration  model

from sklearn.linear_model import LinearRegression

In [190]:
r_model = LinearRegression()

r_model

LinearRegression()

In [191]:
r_model.fit(x_train, y_train)

LinearRegression()

In [192]:
for i, col_name in enumerate(x_train.columns):
    print(i, col_name)

0 cylinders
1 displacement
2 horsepower
3 weight
4 acceleration
5 model_year
6 origin

In [193]:
for i, col_name in enumerate(x_train.columns):
    print(f"the cofficient for {col_name} is {r_model.coef_[i]}")

the cofficient for cylinders is -0.280035169760904
the cofficient for displacement is 0.026703181852386536
the cofficient for horsepower is -0.013017723332907936
the cofficient for weight is -0.007729489161772143
the cofficient for acceleration is 0.10145001444231778
the cofficient for model_year is 0.8598926351081297
the cofficient for origin is 1.5573605042305825

In [194]:
# coefficients are relatively smaller, if independent variable changes slightly thare will be not much difference in prediction.
# this is sometime is called smoother model

In [195]:
from sklearn.metrics import r2_score

In [196]:
y_pred_lr = r_model.predict(x_test)

In [197]:
r2_linear = r2_score(y_test, y_pred_lr)
print(f"r square of linear regression {r2_linear}")

r square of linear regression 0.8347238669135191

In [198]:
# redge regression 

from sklearn.linear_model import Ridge

In [199]:
r_r_model = Ridge(alpha=0.1)

In [200]:
r_r_model.fit(x_train, y_train)

Ridge(alpha=0.1)

In [201]:
for i, col_name in enumerate(x_train.columns):
    print(f"the cofficient for {col_name} is {r_r_model.coef_[i]}")

the cofficient for cylinders is -0.2795032146569732
the cofficient for displacement is 0.026680162476405273
the cofficient for horsepower is -0.01301188709464951
the cofficient for weight is -0.007729008018758181
the cofficient for acceleration is 0.10140068823849827
the cofficient for model_year is 0.8598043044248923
the cofficient for origin is 1.5557607412157453

In [202]:
y_pred_ridge = r_r_model.predict(x_test)
r2_ridge = r2_score(y_test, y_pred_ridge)
print(f"r-square score for ridge regression: {r2_ridge}")

r-square score for ridge regression: 0.8347388547820727

In [203]:
#we dont see much variation in coeff of ridge regression as compared to linear regression

In [204]:
#lasso redgession

In [205]:
from sklearn.linear_model import Lasso

In [206]:
l_r_model = Lasso(alpha=0.5)
l_r_model.fit(x_train, y_train)

Lasso(alpha=0.5)

In [207]:
for i, col_name in enumerate(x_train.columns):
    print(f"the cofficient for {col_name} is {l_r_model.coef_[i]}")

the cofficient for cylinders is -0.0
the cofficient for displacement is 0.0062387009434166415
the cofficient for horsepower is -0.010759763375037482
the cofficient for weight is -0.007024499640457018
the cofficient for acceleration is 0.0
the cofficient for model_year is 0.7523699284139415
the cofficient for origin is 0.0

In [208]:
# 3 features coefficients are 0, lasso helps in feature selaction

In [209]:
y_pred_lasso = l_r_model.predict(x_test)
r2_lasso = r2_score(y_test, y_pred_lasso)
print(f"r-square score for lasso regression: {r2_lasso}")

r-square score for lasso regression: 0.8314806796528442

In [210]:
# elastik regresion 

from sklearn.linear_model import ElasticNet

In [211]:
e_r_model = ElasticNet(alpha=1, l1_ratio=0.5)
e_r_model.fit(x_train, y_train)

ElasticNet(alpha=1)

In [212]:
for i, col_name in enumerate(x_train.columns):
    print(f"the cofficient for {col_name} is {e_r_model.coef_[i]}")

the cofficient for cylinders is -0.0
the cofficient for displacement is 0.005685458661441318
the cofficient for horsepower is -0.01200689964971478
the cofficient for weight is -0.006958734534666874
the cofficient for acceleration is 0.0
the cofficient for model_year is 0.7196630878778915
the cofficient for origin is 0.0

In [213]:
y_pred_elastic = e_r_model.predict(x_test)
r2_elastic = r2_score(y_test, y_pred_elastic)
print(f"r-square score for elastic net regression: {r2_elastic}")

r-square score for elastic net regression: 0.8330933661974431

In [ ]:
#cross validation lasso

In [ ]:
from sklearn.linear_model import LassoCV
Lasso_cv=LassoCV(cv=5)
Lasso_cv.fit(x_train,y_train)

y_pred_lcv=Lasso_cv.predict(x_test)


score = r2_score(y_test, y_pred_lcv)
print("R2 score", score)

R2 score 0.8169961202696704

In [222]:
Lasso_cv.get_params()

{'alphas': None,
 'copy_X': True,
 'cv': 5,
 'eps': 0.001,
 'fit_intercept': True,
 'max_iter': 1000,
 'n_alphas': 100,
 'n_jobs': None,
 'positive': False,
 'precompute': 'auto',
 'random_state': None,
 'selection': 'cyclic',
 'tol': 0.0001,
 'verbose': False}

In [216]:
##cross validation ridge

from sklearn.linear_model import RidgeCV
ridge_cv=RidgeCV(cv=5)
ridge_cv.fit(x_train,y_train)

y_pred_rcv=ridge_cv.predict(x_test)


score = r2_score(y_test, y_pred_rcv)
print("R2 score", score)

R2 score 0.8359338702295104

In [221]:
ridge_cv.get_params()

{'alpha_per_target': False,
 'alphas': (0.1, 1.0, 10.0),
 'cv': 5,
 'fit_intercept': True,
 'gcv_mode': None,
 'scoring': None,
 'store_cv_results': None,
 'store_cv_values': 'deprecated'}

In [217]:
# elastiknet cross validation 

from sklearn.linear_model import ElasticNetCV
elastic_cv = ElasticNetCV(cv=5)
elastic_cv.fit(x_train, y_train)

y_pred_ecv = elastic_cv.predict(x_test)

score = r2_score(y_test, y_pred_ecv)
print("R2 score", score)

R2 score 0.80107262588184

In [224]:
elastic_cv.get_params()

{'alphas': None,
 'copy_X': True,
 'cv': 5,
 'eps': 0.001,
 'fit_intercept': True,
 'l1_ratio': 0.5,
 'max_iter': 1000,
 'n_alphas': 100,
 'n_jobs': None,
 'positive': False,
 'precompute': 'auto',
 'random_state': None,
 'selection': 'cyclic',
 'tol': 0.0001,
 'verbose': 0}